language: php
sudo: false

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

addons:
    sonarcloud:
        organization: "verbanent-public"
        token:
            secure: "MM01z8LC6NToHCv993MwZSsS1PmrnKmMpR3L+c/ndd33ZnMhO0TeQuph5y1F76+fOSpDNh671DwZqZ+RoajRpmjezeOkD3Am2wOBlFFJB5VZqzF3+gE1Ic8NjomE4jiLysERwBuELmJ4nB7CaHo9tUvGqDd71tsBgFIo9+Gz1yan5T7EKBofvtVHaF2Szb18P6j+6GuXUX1wW9h9vDTUuwA8tMOvTqnf5NEL+C08WHpv/ulazZchXMGqV2cnKs5f1t7ifQBtmM22s0OEgdjGgVVZMk/9RUAJliaJ0V2nvWdDiHaBUMQ+pxM4AThxlws+NJrCplhX0xH3dnUM8eAL9fQoW7J+5+zfKLOvq2aAsnhLbgwFvwS2B7ITJKt1vshW4SZ3kSlEuzIt0EaGV6G/15OLznAzzDDcyL4Cbsu890vqta8tJJMXEuRrXj8C84kjohR+DcOKBz8tf0g255eCCDGLppRgv0nJy4cwhrcZMh5jdd7V07LuMW2J33hKIGfrwI3byOLyI0jwXOnhGG7h/SaMYL/WDdBdDiPn2LRxoSOA2vZJ9dxaZOJaK6BOJvNPvSyVWnEq8GA8UsTh8jfXxi4b48+DuBr3hbVDD2XDyOIV61Gyg9kOqz+uROcnyev/V+O7Z5oqg3vvWtTtfO5tzJ6M/nXHiRSG2dNkYbIImAg="

git:
    depth: false

install: composer update --no-interaction --no-suggest --no-progress

script:
    - phpdbg -qrr vendor/bin/phpunit  --coverage-clover phpunit.coverage.xml --log-junit phpunit.report.xml
    - sonar-scanner
