language: php
sudo: false

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

addons:
    sonarcloud:
        organization: "verbanent-public"
        token:
            secure: "AX6klnvTZH6n+1GWmQeJT37qt4OVWaRCECSdW1mNcquE+fScm2EnaTvs6CiCxvCUXttsBRsVJXjEJpzK/QbPdRDFNEGBujlkPu22+4YaGNqyleVAwkFIv5Lq5zrI0YZgUPzegEnxLtPAIrF1FAK6XIa+HB4e8KvbScagTl5fs32VYdrubUy6CiZHgh18YN2uQn2pExcKALJlsRJGpMzOb7t0ktnNCAIIz4XPx7F1mT22681FQLSEN7B2E9mo0cGjWcnVn4od2BEUjkpXXm7fngs1MIHIOwPUo4nQ3fLvCG89glWknmYr8oXvCrH3x7ejVhZeAUL0g8nmcANGv9qnINEnGKftQPK9nq599XtTZSnepgOFixBv8kpGqxBoN+wzTCgbZ6Fg4mPnnOoKnMz1pyKAqfirLCRxaHruuiXJReoeFnRSsLVVOun7ffNkkI2AC1wOgxLSoLTpq4m2KEBJQuZeSZEvaXNv+6jCrL4/5Osyu5JXrumyUuWXG+KLqzMLESlxJYpEG2HGr2DQouu7OAPKQUcmy163twBNXjI2K3mMlxEvYy/HmhS1XlfhBlbl3unuxarqIg5DWWKHGtV/8S9I7I1mfEmZb5MDeGlMDNluJrV29iumYIw3A7jPffbrMXLI976JwsxRuiTCeY20bAw9Z1p0FO933BA4xJCgUZ4="

git:
    depth: false

install: composer update --no-interaction --no-suggest --no-progress

script:
    - phpdbg -qrr vendor/bin/phpunit  --coverage-clover phpunit.coverage.xml --log-junit phpunit.report.xml
    - sonar-scanner
