name: sonarcloud
on:
    push:
        branches: [ main ]
    pull_request:

jobs:
    sonarcloud:
        if: ${{ github.repository == 'verbanent/eloquent-binary-uuid' && (github.event_name != 'pull_request' ||
            github.event.pull_request.head.repo.full_name == github.repository) }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
                with:
                    fetch-depth: 0
            -   uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
                with:
                    php-version: '8.2'
                    coverage: xdebug
            -   run: composer install --no-interaction --no-progress --prefer-dist
            -   run: php -d xdebug.mode=coverage vendor/bin/phpunit --coverage-clover coverage.xml
            -   uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
